version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: apsocial
      POSTGRES_USER: socialuser
      POSTGRES_PASSWORD: socialpass
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
