# Generated by Django 5.0.7 on 2024-08-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chatmessages_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chat_id',
            new_name='chat_room',
        ),
    ]
