# Generated by Django 5.0.7 on 2024-08-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
