# Generated by Django 5.0.7 on 2024-09-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_users_groups_users_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='online',
        ),
    ]
