# Generated by Django 5.0.7 on 2024-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_users_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
