# Generated by Django 5.1.1 on 2024-10-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_users_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='users',
            name='my_followers',
        ),
    ]
