# Generated by Django 5.1.1 on 2024-10-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userfollow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
