# Generated by Django 5.1.3 on 2024-11-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_historysearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historysearch',
            name='searched_username',
        ),
        migrations.AddField(
            model_name='historysearch',
            name='searched_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='searches_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historysearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
