# Generated by Django 5.1.1 on 2024-10-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_userchatname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChatName',
        ),
    ]
