# Generated by Django 5.1.1 on 2024-10-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='custom_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
