# Generated by Django 5.0.7 on 2024-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_date_joined_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
