# Generated by Django 5.0.7 on 2024-09-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_block_user_blockeduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='block_user',
        ),
    ]
